# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Thompson | Technologist & Leader
email:
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about leadership, development and the journal to delivering
  something you care about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marktechson.com" # the base hostname & protocol for your site
twitter_username: marktechson
github_username:  marktechson

# Build settings
markdown: kramdown
