# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hello, I'm Mark
tagline:          'Teaching and Code'
description:      I love to <b>code</b> and <b>teach</b>. I'm building some fun products, too. Want me to speak at your event? Let's talk! <a href="https://twitter.com/marktechson">@marktechson</a>
url:              http://hyde.getpoole.com
# baseurl:          /

author:
  name:           'Mark Techson'
  url:            https://twitter.com/marktechson

paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins: [jekyll-paginate, jekyll-gist]
markdown: kramdown